### PR TITLE
Add startup check for status

### PR DESCRIPTION
**Pull request by hardillb**
Fixes https://github.com/flowforge/flowforge/issues/586

### CODE REVIEW

**Comment by knolleary** [comment]
I'm not sure this PR gets to the bottom of the issue. But I may have missed something.

As far as I can see, we still have the 3 second timeout in `createPod` that will set the state to `started` regardless of what has actually happened. Once that gets set, the platform will show the editor button and the user can click on it - even if the pod is still starting. I don't see how the new logic handles that scenario.

**Comment by hardillb** [comment]
The problem is that we have no idea how long it will take for the pod to be ready, it will depend on if the K8s node it's running has the right version of the container cached, if it doesn't it will need to pull it from the container store, how long that takes is an unknown.

And the only thing we can do is poll the state and the `details` function is the best place to do that. So I think the question is what should the `createPod` return other than `started` (`starting`?)

**Comment by lu4t** [comment]
> The problem is that we have no idea how long it will take for the pod to be ready, it will depend on if the K8s node it's running has the right version of the container cached, if it doesn't it will need to pull it from the container store, how long that takes is an unknown.
> 
> And the only thing we can do is poll the state and the `details` function is the best place to do that. So I think the question is what should the `createPod` return other than `started` (`starting`?)

sorry to jump into the conversation, but I was wondering while reading: wouldn't it be possible to use a lifecycle handler in this case?

https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by hardillb** [comment]
@lu4t no problem. That might work later when we have a mechanism for projects to asynchronously check in (probably coming with the messaging support we are working on, but I don't think it will work just yet). We also need to think how it would work with the other 2 container drivers (docker and localfs)

**Comment by knolleary** [comment]
@hardillb what if we just remove the `setTimeout` altogether? Leave it in `starting` state - the code change in this PR will get it back to the right `started` state once it detects NR running.

**Comment by hardillb** [comment]
Yep, I had just about come to the same conclusion.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
